# Generated by Django 4.2.9 on 2024-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summory',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
