# Generated by Django 4.2.9 on 2024-01-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_summory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
