# Generated by Django 4.2.9 on 2024-01-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
